const List HOLIDAY = [
  {
    'year': '2021',
    'holiday': [
      {'month': '01', 'day': '01', 'dayNm': '신정'},
      {'month': '02', 'day': '11', 'dayNm': '설연휴'},
      {'month': '02', 'day': '12', 'dayNm': '설날'},
      {'month': '02', 'day': '13', 'dayNm': '설연휴'},
      {'month': '03', 'day': '01', 'dayNm': '삼일절'},
      {'month': '03', 'day': '09', 'dayNm': '제20대 대통령선거'},
      {'month': '05', 'day': '05', 'dayNm': '어린이날'},
      {'month': '05', 'day': '19', 'dayNm': '부처님오신날'},
      {'month': '06', 'day': '06', 'dayNm': '현충일'},
      {'month': '08', 'day': '15', 'dayNm': '광복절'},
      {'month': '08', 'day': '16', 'dayNm': '대체공휴일'},
      {'month': '09', 'day': '20', 'dayNm': '추석연휴'},
      {'month': '09', 'day': '21', 'dayNm': '추석'},
      {'month': '09', 'day': '22', 'dayNm': '추석연휴'},
      {'month': '10', 'day': '03', 'dayNm': '개천절'},
      {'month': '10', 'day': '04', 'dayNm': '대체공휴일'},
      {'month': '10', 'day': '09', 'dayNm': '한글날'},
      {'month': '10', 'day': '11', 'dayNm': '대체공휴일'},
      {'month': '12', 'day': '25', 'dayNm': '성탄절'},
    ]
  },
  {
    'year': '2022',
    'holiday': [
      {'month': '01', 'day': '01', 'dayNm': '신정'},
      {'month': '01', 'day': '31', 'dayNm': '설연휴'},
      {'month': '02', 'day': '01', 'dayNm': '설날'},
      {'month': '02', 'day': '02', 'dayNm': '설연휴'},
      {'month': '03', 'day': '01', 'dayNm': '삼일절'},
      {'month': '03', 'day': '09', 'dayNm': '제20대 대통령선거'},
      {'month': '05', 'day': '05', 'dayNm': '어린이날'},
      {'month': '05', 'day': '08', 'dayNm': '부처님오신날'},
      {'month': '06', 'day': '01', 'dayNm': '제8회 전국동시지방선거'},
      {'month': '06', 'day': '06', 'dayNm': '현충일'},
      {'month': '08', 'day': '15', 'dayNm': '광복절'},
      {'month': '09', 'day': '09', 'dayNm': '추석연휴'},
      {'month': '09', 'day': '10', 'dayNm': '추석'},
      {'month': '09', 'day': '11', 'dayNm': '추석연휴'},
      {'month': '09', 'day': '12', 'dayNm': '대체공휴일'},
      {'month': '10', 'day': '03', 'dayNm': '개천절'},
      {'month': '10', 'day': '09', 'dayNm': '한글날'},
      {'month': '10', 'day': '10', 'dayNm': '대체공휴일'},
      {'month': '12', 'day': '25', 'dayNm': '성탄절'},
    ]
  },
  {
    'year': '2023',
    'holiday': [
      {'month': '01', 'day': '01', 'dayNm': '신정'},
      {'month': '01', 'day': '21', 'dayNm': '설연휴'},
      {'month': '01', 'day': '22', 'dayNm': '설날'},
      {'month': '01', 'day': '23', 'dayNm': '설연휴'},
      {'month': '01', 'day': '24', 'dayNm': '대체공휴일'},
      {'month': '03', 'day': '01', 'dayNm': '삼일절'},
      {'month': '05', 'day': '05', 'dayNm': '어린이날'},
      {'month': '05', 'day': '27', 'dayNm': '부처님오신날'},
      {'month': '06', 'day': '06', 'dayNm': '현충일'},
      {'month': '08', 'day': '15', 'dayNm': '광복절'},
      {'month': '09', 'day': '28', 'dayNm': '추석연휴'},
      {'month': '09', 'day': '29', 'dayNm': '추석'},
      {'month': '09', 'day': '30', 'dayNm': '추석연휴'},
      {'month': '10', 'day': '03', 'dayNm': '개천절'},
      {'month': '10', 'day': '09', 'dayNm': '한글날'},
      {'month': '12', 'day': '25', 'dayNm': '성탄절'},
    ],
  },
  {
    'year': '2024',
    'holiday': [
      {'month': '01', 'day': '01', 'dayNm': '신정'},
      {'month': '02', 'day': '09', 'dayNm': '설연휴'},
      {'month': '02', 'day': '10', 'dayNm': '설날'},
      {'month': '02', 'day': '11', 'dayNm': '설연휴'},
      {'month': '03', 'day': '01', 'dayNm': '삼일절'},
      {'month': '04', 'day': '10', 'dayNm': '22대 국회의원선거'},
      {'month': '05', 'day': '05', 'dayNm': '어린이날'},
      {'month': '05', 'day': '15', 'dayNm': '부처님오신날'},
      {'month': '06', 'day': '06', 'dayNm': '현충일'},
      {'month': '08', 'day': '15', 'dayNm': '광복절'},
      {'month': '09', 'day': '16', 'dayNm': '추석연휴'},
      {'month': '09', 'day': '17', 'dayNm': '추석'},
      {'month': '09', 'day': '18', 'dayNm': '추석연휴'},
      {'month': '10', 'day': '03', 'dayNm': '개천절'},
      {'month': '10', 'day': '09', 'dayNm': '한글날'},
      {'month': '12', 'day': '25', 'dayNm': '성탄절'},
    ],
  },
  {
    'year': '2025',
    'holiday': [
      {'month': '01', 'day': '01', 'dayNm': '신정'},
      {'month': '01', 'day': '28', 'dayNm': '설연휴'},
      {'month': '01', 'day': '29', 'dayNm': '설날'},
      {'month': '01', 'day': '30', 'dayNm': '설연휴'},
      {'month': '03', 'day': '01', 'dayNm': '삼일절'},
      {'month': '05', 'day': '05', 'dayNm': '부처님오신날'},
      {'month': '05', 'day': '05', 'dayNm': '어린이날'},
      {'month': '05', 'day': '27', 'dayNm': '부처님오신날'},
      {'month': '06', 'day': '06', 'dayNm': '현충일'},
      {'month': '08', 'day': '15', 'dayNm': '광복절'},
      {'month': '10', 'day': '03', 'dayNm': '개천절'},
      {'month': '10', 'day': '05', 'dayNm': '추석연휴'},
      {'month': '10', 'day': '06', 'dayNm': '추석'},
      {'month': '10', 'day': '07', 'dayNm': '추석연휴'},
      {'month': '10', 'day': '09', 'dayNm': '한글날'},
      {'month': '12', 'day': '25', 'dayNm': '성탄절'},
    ]
  },
];